spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: user
      password: password
      database: intraday-trading-management-api-database